archetype.groupId=io.sermant
archetype.artifactId=sermant-template-archetype
archetype.version=2.1.0
groupId=io.sermant
artifactId=first-plugin
version=2.1.0
package=io.sermant
excludePatterns=.idea/**,.idea/libraries/*,**/*.iml,README.md